### PR TITLE
22w03a

### PR DESCRIPTION
**Pull request by DragonEggBedrockBreaking**
Update to 22w03a - current version crashes on startup since it Shadows a field that no longer exists, and this fixes that.

### CODE REVIEW

**Comment by JRoy** [comment]
Starlight doesn't accept update PRs from outside contributors. Sorry.

**Comment by Spottedleaf** [comment]
jroy is an idiot
there's no 1.19 dev branch to merge this to, and right now i don't think it's worth updating, only diff is log4j, i will handle this on a later snapshot

**Comment by DragonEggBedrockBreaking** [comment]
> jroy is an idiot
> there's no 1.19 dev branch to merge this to, and right now i don't think it's worth updating, only diff is log4j, i will handle this on a later snapshot

22w03a is not a 1.19 snapshot, it is a 1.18.2 snapshot.

**Comment by JRoy** [comment]
> jroy is an idiot

you're literally french canadian

**Pull request closed without merging**
