### PR TITLE
Update for Gradle 7

### PR DESCRIPTION
**Pull request by WhyDoWeWonder**
Removed use of deprecated Gradle features in the build script, allowing build to work with Gradle 7.

### CODE REVIEW

**Review by ghost — COMMENTED** [review]
It builds fine with the deprecated features. This also won't work as Gradle 7 is required for this.

**Comment by DragonEggBedrockBreaking** [comment]
> This also won't work as Gradle 7 is required for this.

You can install gradle 7 on your own computer and compile with that. This is necessar if you use JDK 16.

**Comment by Spottedleaf** [comment]
This change was made in https://github.com/Spottedleaf/Starlight/commit/c265c51e5a4372f267979354ea3cdef6cff2b1b8. It will arrive when 1.17 arrives.

**Comment by yannicklamprecht** [comment]
Then update the Gradle wrapper!

**Comment by ghost** [comment]
> > This also won't work as Gradle 7 is required for this.
> 
> You can install gradle 7 on your own computer and compile with that. This is necessar if you use JDK 16.

No, you would have to update the Gradle wrapper first.

**Comment by DragonEggBedrockBreaking** [comment]
> > > This also won't work as Gradle 7 is required for this.
> > 
> > 
> > You can install gradle 7 on your own computer and compile with that. This is necessar if you use JDK 16.
> 
> No, you would have to update the Gradle wrapper first.

No you wouldn’t? I use JDK 16 and build all my mods with Gradle 7.0.2, which is installed on my computer. You use `gradle build` rather than `gradlew build` to use the gradle on your computer.

**Comment by DragonEggBedrockBreaking** [comment]
> Then update the Gradle wrapper!

On the 1.17 branch, the wrapper is already on 7.0.2:
https://github.com/Spottedleaf/Starlight/blob/c265c51e5a4372f267979354ea3cdef6cff2b1b8/gradle/wrapper/gradle-wrapper.properties#L3
You just need to change a few characters most of the time, and don’t need to touch the shell script/batch file. It’s just that the ide sometimes does that automatically, or some people re-generate the grade wrapper (with the gradle command), which edits those files (and the wrapper .jar file).

**Comment by ghost** [comment]
> > > > This also won't work as Gradle 7 is required for this.
> > > 
> > > 
> > > You can install gradle 7 on your own computer and compile with that. This is necessar if you use JDK 16.
> > 
> > 
> > No, you would have to update the Gradle wrapper first.
> 
> No you wouldn’t? I use JDK 16 and build all my mods with Gradle 7.0.2, which is installed on my computer. You use `gradle build` rather than `gradlew build` to use the gradle on your computer.

Oh, I'm not that experienced with gradle. Either way, the gradle wrapper should've been updated anyways.

**Comment by DragonEggBedrockBreaking** [comment]
> Oh, I'm not that experienced with gradle. Either way, the gradle wrapper should've been updated anyways.

As I said, the gradle wrapper version has been bumped -it is just one number that needs to be changed, it is just that the ide sometimes regenerates the shell script, batch file and jar file as well.

**Comment by zml2008** [comment]
[the method yall are whining about was added 8 years ago](https://github.com/gradle/gradle/blame/5ec3f672ed600a86280be490395d70b7bc634862/subprojects/core-api/src/main/java/org/gradle/api/file/CopySpec.java#L143)

please don't review PRs when you have no idea what you're talking about

**Pull request closed without merging**
