### PR TITLE
Add GitHub Actions To Build On Push

### PR DESCRIPTION
**Pull request by DragonEggBedrockBreaking**
Alternative to #30, and imo this is better. Reasons:

- this builds only on linux (because windows is pointless for this)
- this builds only on jdk 11
- this is much smaller and simpler

### CODE REVIEW

**Review by katekerllenevich — APPROVED** [review]

**Review by Titaniumtown — APPROVED** [review]

**Review by thecoder-001 — APPROVED** [review]

**Comment by DragonEggBedrockBreaking** [comment]
New changes:
- Updated actions to build with JDK 16 due to now being on 1.17
- Removed the executable gradlew part due to now being executable by default

**Review by MonoSyntax — APPROVED** [review]

**Review by JFronny — APPROVED** [review]

**Comment by OakBricks-old** [comment]
just a question, but when is this gonna be merged into mainline?

**Comment by Zarkoob** [comment]
@DragonEggBedrockBreaking I don't think this issue was ever merged thinking both were dupe?

**Comment by DragonEggBedrockBreaking** [comment]
> @DragonEggBedrockBreaking I don't think this issue was ever merged thinking both were dupe?

What? I don’t understand what you mean. Could you please rephrase?

**Comment by Kichura** [comment]
Perhaps add github actions for 1.18 branch as that version uses JDK 17 now?

**Comment by DragonEggBedrockBreaking** [comment]
> Perhaps add github actions for 1.18 branch as that version uses JDK 17 now?

When 1.18 is released, and the 1.18 branch is merged into this branch, I will edit actions to use Java 17.

**Comment by Kichura** [comment]
> > Perhaps add github actions for 1.18 branch as that version uses JDK 17 now?
> 
> 
> 
> When 1.18 is released, and the 1.18 branch is merged into this branch, I will edit actions to use Java 17.

1.18 has been released since weeks now or so - just to point this one out i suppose.

**Comment by Spottedleaf** [comment]
GH actions is generally too confusing for users to use. I also don't want to encourage people to use non-release builds.

**Pull request closed without merging**
