### PR TITLE
Add Mixin patch for Create

### LINKED ISSUE #45: Starlight Forge 1.0.0-RC + Create 0.3.1 conflict
https://pastebin.com/Bvn5jx39

https://pastebin.com/cKbK8UHp

https://pastebin.com/eTbphx1i

Different crashes each time, I'm not sure which mod is at fault out of the two so posting on both. 

It seemed to happen regardless of if I had creates "experimentalRendering" option set to on or off.

### PR DESCRIPTION
**Pull request by AeiouEnigma**
This patch modifies Create's WrappedChunk class to implement Starlight's ExtendedChunk interface, and adds default implementations of ExtendedWorld's methods partially to WorldMixin and partially to ExtendedWorld itself. WorldMixin now includes CustomLightHandler methods, while ExtendedWorld has default method bodies for getChunkAtImmediately and getAnyChunkImmediately. Should close #45 and #55. This PR also adds a Mixin plugin class, which disables the Create compatibility module when Create is not installed.

Create's devs have determined that it isn't appropriate for them to modify their code to support Starlight. A relatively simple mixin-based compatibility patch can be easily shipped with Starlight to achieve compatibility.

This PR has not been extensively tested yet.

### CODE REVIEW

**Comment by BugmanBugman** [comment]
Can confirm this fixes crashes for me

**Comment by AeiouEnigma** [comment]
Special attention should be paid to my one-line change in StarLightInterface$LightQueue.queueSectionChange, which calls Math.floorMod to avoid crashing with negative SectionPos y-coordinates. It's a change which solves the problem at hand, but which I suspect may in theory cause other issues with other mods.

**Comment by Spottedleaf** [comment]
> 
> 
> Special attention should be paid to my one-line change in StarLightInterface$LightQueue.queueSectionChange, which calls Math.floorMod to avoid crashing with negative SectionPos y-coordinates. It's a change which solves the problem at hand, but which I suspect may in theory cause other issues with other mods.

Out of bound section changes should never ever ever ever ever ever ever EVER EVER be queued. Vanilla doesn't do it, vanilla in 1.17 doesn't do it, vanilla doesn't expect it, and it simply makes zero sense to EVER queue it for a section that just does not exist.

**Comment by AeiouEnigma** [comment]
Closing this PR. As it stands, it isn't suitable to be merged. I will rework this and resubmit it at a later date.

**Pull request closed without merging**
